on:
  # TODO:
  push:
  workflow_dispatch:

jobs:
  define-packages:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - name: Discover Packages
        id: packages
        run: |
          echo "packages=$(find . -name "ato.yaml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  test-and-publish:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    needs: define-packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      # FIXME: handle deps properly
      # ideally it'd determine if the package is in the same repo and, if so,
      # install via file instead
      - uses: atopile/setup-atopile@v1.6
        working-directory: ${{ matrix.package }}
      - run: ato sync
        working-directory: ${{ matrix.package }}
      - run: ato build
        working-directory: ${{ matrix.package }}

      # Publish package
      - uses: atopile/publish-package@v1
        with:
          package-entrypoint: ${{ matrix.package }}
          skip-duplicate-versions: true
          package-version: "" # Use the embedded version key
