on:
  # TODO:
  push:
  workflow_dispatch:

jobs:
  define-packages:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - name: Discover Packages
        id: packages
        run: |
          # echo "packages=$(find . -name "ato.yaml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
          echo 'packages=["packages/addressable-leds"]' >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: define-packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}

    steps:
      - uses: actions/checkout@v4

      # TODO: use the docker image instead
      - uses: docker://ghcr.io/atopile/atopile:latest
        with:
          entrypoint: bash
          args: |
            ato sync
            ato build --frozen
