on:
  # TODO:
  push:
  workflow_dispatch:

jobs:
  define-packages:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - name: Discover Packages
        id: packages
        run: |
          echo "packages=$(find . -name "ato.yaml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
          # echo 'packages=["packages/addressable-leds"]' >> "$GITHUB_OUTPUT"

  test:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    needs: define-packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: atopile/run-atopile@main
        with:
          # TODO: re-add ato sync
          args: "ato build --frozen ${{ matrix.package }}"


  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - define-packages

    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}
      fail-fast: false

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: atopile/publish-package@main
        with:
          working-directory: ${{ matrix.package }}
          skip-duplicate-versions: true
          package-version: ""  # Use the embedded version key
