on:
  # TODO:
  push:
  workflow_dispatch:

jobs:
  define-packages:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.packages.outputs.packages }}

    steps:
      - name: Discover Packages
        id: packages
        run: |
          echo "packages=$(find . -name "ato.yaml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: define-packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}

    steps:
      - run: echo "package=$package"
